"""
Regenerate osmosis/model.pyi from registered wrappers and OpenStudio SDK classes.

Usage
-----
    python -m osmosis._gen_stubs

Run after adding any new @register_custom_wrapper decorated class.
Commit model.pyi alongside the new wrapper file.
"""
from __future__ import annotations

import importlib
import pkgutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import osmosis  # noqa: E402

package_path = Path(osmosis.__file__).parent

for _finder, module_name, _is_pkg in pkgutil.iter_modules([str(package_path)]):
    if module_name.startswith("_"):
        continue
    try:
        importlib.import_module(f"osmosis.{module_name}")
    except Exception:
        pass

from osmosis.registry import _registry, _snake_registry, _to_snake  # noqa: E402
import openstudio  # noqa: E402

# ---------------------------------------------------------------------------

HEADER = """\
# osmosis/model.pyi
# AUTO-GENERATED by osmosis/_gen_stubs.py — do not edit manually.
# Regenerate with:  python -m osmosis._gen_stubs

from typing import Any

from .air_loop import AirLoopHVAC
from .plant_loop import PlantLoop
from .schedule_constant import ScheduleConstant
from .base import OsmObject
from .manager import ComponentManager
"""

MODEL_HEADER = """\

class Model:
    @classmethod
    def new(cls) -> Model: ...
    @classmethod
    def load(cls, path: str) -> Model: ...
    def save(self, path: str, overwrite: bool = False) -> None: ...
    def save_as(self, path: str) -> None: ...
    def create_constant_schedule(self, name: str, value: float, *, unit_type: str | None = None, lower_limit_value: float | None = None, upper_limit_value: float | None = None, numeric_type: str = "Continuous") -> ScheduleConstant: ...
    @property
    def raw(self) -> Any: ...
    @property
    def air_loop(self) -> ComponentManager[AirLoopHVAC]: ...
    @property
    def air_loops(self) -> list[AirLoopHVAC]: ...
    @property
    def plant_loops(self) -> list[PlantLoop]: ...
    def __getattr__(self, name: str) -> Any: ...
"""

imports: list[str] = []
properties: list[str] = []

typed_properties: dict[str, str] = {}

for snake_name, sdk_name in sorted(_snake_registry.items()):
    wrapper_cls = _registry.get(sdk_name)
    if wrapper_cls is None:
        continue
    module = wrapper_cls.__module__.split(".")[-1]
    cls_name = wrapper_cls.__name__
    imports.append(f"from .{module} import {cls_name}")
    typed_properties[snake_name] = (
        f"    @property\n"
        f"    def {snake_name}(self) -> ComponentManager[{cls_name}]: ..."
    )

for sdk_name in sorted(dir(openstudio.model)):
    if (
        sdk_name.startswith("_")
        or sdk_name.startswith("Optional")
        or sdk_name.endswith("Vector")
    ):
        continue
    sdk_obj = getattr(openstudio.model, sdk_name, None)
    if not isinstance(sdk_obj, type):
        continue
    snake_name = _to_snake(sdk_name)
    if "_" not in snake_name or snake_name in typed_properties:
        continue
    typed_properties[snake_name] = (
        f"    @property\n"
        f"    def {snake_name}(self) -> ComponentManager[OsmObject]: ..."
    )

properties = [typed_properties[name] for name in sorted(typed_properties)]

stub = (
    HEADER
    + "\n".join(sorted(set(imports)))
    + MODEL_HEADER
    + "\n".join(properties)
    + "\n"
)

out_path = package_path / "model.pyi"
out_path.write_text(stub, encoding="utf-8")
print(f"Wrote {len(properties)} properties to {out_path}")
